# Generated by Django 2.1.7 on 2019-06-11 22:51

import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpasswordcode',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='christmas_story_seen',
        ),
        migrations.AlterField(
            model_name='achievementmembership',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='achievementmembership',
            name='new',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='bordermembership',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bordermembership',
            name='new',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='titlemembership',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='titlemembership',
            name='new',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_id',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='christmas_achievement_1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='christmas_achievement_2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='score_articles_seen',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='{}', max_length=100), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userfriendship',
            name='block',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userfriendship',
            name='follow',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='ResetPasswordCode',
        ),
    ]
