# Generated by Django 2.1.7 on 2019-09-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_auto_20190611_2251'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_id',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
