# Generated by Django 2.0.7 on 2019-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('post_vote', 'post vote'), ('user_follow', 'user follow'), ('user_post', 'new user post'), ('tag_content', 'new tag content'), ('private_message', 'new private message'), ('achievement', 'new achievement')], max_length=999)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('new', models.BooleanField(default=True)),
                ('notification_message', models.CharField(max_length=999)),
            ],
        ),
    ]
