# Generated by Django 2.0.7 on 2019-06-11 22:44

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('release_type', models.CharField(choices=[('release', 'release'), ('event', 'event')], max_length=999)),
                ('title', models.CharField(max_length=999)),
                ('snippet', models.CharField(blank=True, max_length=999, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=999, null=True)),
                ('external_link', models.CharField(blank=True, max_length=999, null=True)),
                ('important_tags', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, default=None, force_lowercase=True, help_text='Enter a comma-separated tag string', related_name='release_important_tags', to='general.CustomTag')),
                ('other_tags', tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, default=None, force_lowercase=True, help_text='Enter a comma-separated tag string', related_name='release_other_tags', to='general.CustomTag')),
                ('review_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_link', to='publication.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default=None, max_length=100, null=True)),
                ('image_type', models.CharField(choices=[('gallery', 'Gallery'), ('main', 'Main'), ('thumbnail', 'Thumbnail')], default='gallery', max_length=100)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_images', to='releases.Release')),
            ],
        ),
    ]
