# Generated by Django 2.0.7 on 2019-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatreonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=None, max_length=999, null=True)),
                ('thumbnail', models.CharField(default=None, max_length=999, null=True)),
                ('minimum_level_needed', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatreonOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=999, null=True)),
                ('minimum_level_needed', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatreonUnlockedPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_level_needed', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=999, null=True)),
                ('minimum_level_needed', models.IntegerField(default=1)),
            ],
        ),
    ]
