# Generated by Django 2.0.7 on 2019-06-11 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patreon', '0001_initial'),
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patreonunlockedpublication',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patreon_publication', to='publication.Publication'),
        ),
        migrations.AddField(
            model_name='patreonoption',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_option', to='patreon.Survey'),
        ),
    ]
