# Generated by Django 2.1.7 on 2019-06-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('banner', 'banner'), ('widget', 'widget')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='submission_type',
            field=models.CharField(choices=[('inapropiado', 'inapropiado'), ('empresa', 'empresa'), ('tecnico', 'tecnico'), ('particular', 'particular'), ('otros', 'otros'), ('patreon_link', 'patreon_link')], max_length=100),
        ),
    ]
