# Generated by Django 2.1.7 on 2019-09-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20190611_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='submission_type',
            field=models.CharField(choices=[('patreon_link', 'patreon_link'), ('particular', 'particular'), ('tecnico', 'tecnico'), ('empresa', 'empresa'), ('inapropiado', 'inapropiado'), ('otros', 'otros')], max_length=100),
        ),
    ]
