# Generated by Django 2.1.7 on 2019-09-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20190909_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('widget', 'widget'), ('banner', 'banner')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='submission_type',
            field=models.CharField(choices=[('patreon_link', 'patreon_link'), ('empresa', 'empresa'), ('particular', 'particular'), ('tecnico', 'tecnico'), ('inapropiado', 'inapropiado'), ('otros', 'otros')], max_length=100),
        ),
    ]
