# Generated by Django 2.1.7 on 2019-09-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20190909_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='submission_type',
            field=models.CharField(choices=[('tecnico', 'tecnico'), ('empresa', 'empresa'), ('otros', 'otros'), ('patreon_link', 'patreon_link'), ('particular', 'particular'), ('inapropiado', 'inapropiado')], max_length=100),
        ),
    ]
