# Generated by Django 2.0.7 on 2019-06-11 22:44

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProsAndCons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pro', 'pro'), ('con', 'contra')], default=None, max_length=100, null=True)),
                ('content', models.CharField(default=None, max_length=9999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('publication_type', models.CharField(choices=[('noticia', 'noticia'), ('opinion', 'opinion'), ('curiosidad', 'curiosidad'), ('análisis', 'análisis'), ('artículo_premium', 'artículo_premium'), ('análisis_premium', 'análisis_premium')], max_length=100)),
                ('slug', models.SlugField()),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('game_release_name', models.CharField(blank=True, default=None, max_length=100, null=None)),
                ('game_release_date', models.DateTimeField(blank=True, null=None)),
                ('timestamp', models.DateTimeField(blank=True, null=None)),
                ('content', froala_editor.fields.FroalaField()),
                ('click_score', models.IntegerField()),
                ('masonry_snippet', models.CharField(default=None, max_length=140, null=True)),
                ('masonry_size', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default=None, max_length=9999, null=True)),
                ('image_type', models.CharField(choices=[('masonry', 'masonry'), ('main', 'main'), ('search', 'search'), ('thumbnail', 'thumbnail')], max_length=100)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publication.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('adiccion', 'ADICCIÓN'), ('ambientacion', 'AMBIENTACIÓN'), ('combate', 'COMBATE'), ('dificultad', 'DIFICULTAD'), ('equipo', 'EQUIPO'), ('estrategia', 'ESTRATEGIA'), ('terror', 'TERROR'), ('puzzles', 'PUZZLES'), ('monstruos', 'MONSTRUOS'), ('narrativa', 'NARRATIVA')], max_length=100)),
                ('value', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('description', models.CharField(default=None, max_length=999, null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='publication.Publication')),
            ],
        ),
    ]
