# Generated by Django 2.0.7 on 2019-06-11 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='available_platform_tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, default=None, force_lowercase=True, help_text='Enter a comma-separated tag string', related_name='available_platform_tags', to='general.CustomTag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='developer_tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, default=None, force_lowercase=True, help_text='Enter a comma-separated tag string', related_name='developer_tags', to='general.CustomTag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='genre_tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, default=None, force_lowercase=True, help_text='Enter a comma-separated tag string', related_name='genre_tags', to='general.CustomTag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher_tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, default=None, force_lowercase=True, help_text='Enter a comma-separated tag string', related_name='publisher_tags', to='general.CustomTag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='review_platform_tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, default=None, force_lowercase=True, help_text='Enter a comma-separated tag string', related_name='review_platform_tags', to='general.CustomTag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, default=None, force_lowercase=True, help_text='Enter a comma-separated tag string', related_name='tags', to='general.CustomTag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_tag',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, default=None, force_lowercase=True, help_text='Enter a comma-separated tag string', related_name='title_tag', to='general.CustomTag'),
        ),
        migrations.AddField(
            model_name='prosandcons',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros_and_cons', to='publication.Publication'),
        ),
    ]
