# Generated by Django 2.1.7 on 2019-06-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20190611_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='timestamp',
            new_name='publication_date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='click_score',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('noticia', 'noticia'), ('articulo', 'artículo'), ('análisis', 'análisis')], max_length=100),
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='image_type',
            field=models.CharField(choices=[('main', 'main'), ('masonry', 'masonry'), ('search', 'search'), ('thumbnail', 'thumbnail'), ('rrss', 'rrss')], max_length=100),
        ),
        migrations.AlterField(
            model_name='publicationimage',
            name='path',
            field=models.ImageField(default=None, null=True, upload_to='', max_length=9999),
        ),
    ]
